config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :reports
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "news/data"
  get "news/index"
  # get "pages/data"
  # get "pages/home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  mount_uploader :image, ImageUploader

end 

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 100000 }
  mount_uploader :image, ImageUploader

end 

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :reports, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  require "open-uri"
    def index
      api = Rails.application.credentials.news_api:a16a9bc6a6df47fdb27cabf988017ecd
      uri = "https://newsapi.org/v2/top-headlines?country=jp&apiKey=a16a9bc6a6df47fdb27cabf988017ecd"
      article_serialized = open(uri).read
      @articles = JSON.parse(article_serialized)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  require "open-uri"
    def home
      # redirect_to reports_path if logged_in?
      @reports = Report.paginate(page: params[:page], per_page: 5).order("created_at DESC")
      @random = Report.order("RAND()").limit(6)

      api = Rails.application.credentials.news_api:a16a9bc6a6df47fdb27cabf988017ecd
      uri = "http://newsapi.org/v2/top-headlines?country=jp&category=business&apiKey=a16a9bc6a6df47fdb27cabf988017ecd"
      article_serialized = open(uri).read
      @articles = JSON.parse(article_serialized)
    end

  # require "open-uri"
  #   def home
  #     api = Rails.application.credentials.news_api:a16a9bc6a6df47fdb27cabf988017ecd
  #     uri = "https://newsapi.org/v2/top-headlines?country=jp&apiKey=a16a9bc6a6df47fdb27cabf988017ecd"
  #     report_serialized = open(uri).read
  #     @reports = JSON.parse(report_serialized)
  #   end

  
  def about
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  
  def show
    @reports = Report.paginate(page: params[:page], per_page: 5)
    @random = Report.order("RAND()").limit(6)
  end

  
  def index
    @reports = Report.paginate(page: params[:page], per_page: 5)
    @random = Report.order("RAND()").limit(6)
  end

  def new
    @report = Report.new
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    @report.user = current_user
    if @report.save
      flash[:notice] = "Report was created successfully."
      redirect_to @report
    else
      render 'new'
    end
  end

  def update
    if @report.update(report_params)
      flash[:notice] = "Report was updated successfully."
      redirect_to @report
    else
      render 'edit'
    end
  end

  def destroy
    @report.destroy
    redirect_to reports_path
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:title, :description, :image)
  end

  def require_same_user
    if current_user != @report.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own report"
      redirect_to @report
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    # @reports = @user.reports
    @reports = @user.reports.paginate(page: params[:page], per_page: 5)
    @random = Report.order("RAND()").limit(6)
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the AKI Blog #{@user.username}, you have successfully signed up"
      redirect_to reports_path
    else 
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated reports successfully deleted"
    redirect_to reports_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @article %>
  <%= form_with(model: @article, local: true) do |f| %>
    <div class="contents row">
      <div class="contact-form">
        <div class="item">
          <p>
            <%= f.label :title ,class:"label" %><br/><br/>
            <%= f.text_field :title %>
          </p>
        </div>
        <div class="item">
          <p>
            <%= f.label :image, class:"label" %><br/><br/>
            <%= f.file_field :image%>
          </p>
        </div>
        <div class="item">
          <p>
            <%= f.label :description, class:"label" %><br/><br/>
            <%= f.text_area :description %>
          </p>
        </div>
        <div class="item no-label">
          <%= f.submit class:"label" %>
        </div>

        <div class="item no-label">
          <%= link_to '[ Cancel and return to articles listing ]', articles_path, class:"label" %>
        </div>
      </div>
    </div>
  <% end %> 
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkiBlg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- navigation -->
    <nav class="nav">
      <div class="nav-menu flex-row">
        <div class="nav-brand">
          <%= link_to "AKI BLOG", root_path, class: "text-gray", id: "logo" %>
        </div>
        <div class="toggle-collapse">
          <div class="toggle-icons">
            <i class="fas fa-bars"></i>
          </div>
        </div>
        <div>
          <ul class="nav-items">
            <li class="nav-link">
              <a><%= link_to "Author", users_path %></a>
            </li>
            <li class="nav-link">
              <% if logged_in? %>
                <a><%= link_to "Create new report", new_report_path, class: "dropdown-item" %></a>
              <% end %> 
            </li>
            <li class="nav-link">
              <a><%= link_to "View reports", reports_path %></a>
            </li>
            <% if logged_in? %>
              <li class="nav-link">
                <h2><%= "Admin" if current_user.admin? %> User :[<%= link_to current_user.username, user_path(current_user)%>]</h2>
              </li>
              <li class="nav-link">
                <a><%= link_to 'Logout', logout_path, method: :delete %></a>
              </li>
            <% else %>
              <li class="nav-link">
                <a><%= link_to 'Log in', login_path %></a>
              </li>
              <li class="nav-link">
                <a><%= link_to 'Sign up', signup_path %></a>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="social text-gray">
          <a href="#"><i class="fab fa-facebook-f"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a> 
          <a href="#"><i class="fab fa-youtube"></i></a>
        </div>
      </div>
    </nav>
    
  <!-- end navigation -->
    <%= render 'layouts/messages' %>
    <%= yield %>

  <!-- Footer -->

    <footer class="footer">
      <div class="container">
        <div class="about-us" data-aos="fade-right" data-aos-delay="200">
          <h2>About us</h2>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
        </div>
        <div class="newsletter" data-aos="fade-right" data-aos-delay="200">
          <h2>Newsletter</h2>
          <p>Stay update with our latest</p>
          <div class="form-element">
            <input type="text" placeholder="Email"><span><i class="fas fa-chevron-right"></i></span>
          </div>
        </div>
        <div class="instagram" data-aos="fade-left" data-aos-delay="200">
          <h2>Instagram</h2>
          <div class="flex-row">
            <%= image_tag asset_path("thumb-card3.png", alt: "insta1") %>
            <%= image_tag asset_path("thumb-card4.png", alt: "insta2") %>
            <%= image_tag asset_path("thumb-card5.png", alt: "insta3") %>
          </div>
          <div class="flex-row">
            <%= image_tag asset_path("thumb-card6.png", alt: "insta4") %>
            <%= image_tag asset_path("thumb-card7.png", alt: "insta5") %>
            <%= image_tag asset_path("thumb-card8.png", alt: "insta6") %>
          </div>
        </div>
        <div class="follow" data-aos="fade-right" data-aos-delay="200">
          <h2>Follow us</h2>
          <p>Let us be Social</p>
          <div>
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-youtube"></i>
          </div>
        </div>
      </div>
      <div class="rights flex-row">
        <h4 class="text-gray">
          Copyright ©︎2020 All rights reserved made by Aki BLG
          <a href="#" target="_black"> <i class="fab fa-youtube"></i>Channel</a>
        </h4>
      </div>
      <div class="move-up">
        <span><i class="fas fa-arrow-circle-up fa-2x"></i></span>
      </div>
    </footer>

  <!-- XX Footer -->
  </body>
</html>

app/views/pages/home.html.erb
<!-- main site section -->

  <main>

    <!-- Site title -->

    <section class="site-title">
      <div class="site-background" data-aos="fade-up" data-aos-delay="100">
        <h3>Tours & Travels</h3>
        <h1>Amazing Place on Earth</h1>
        <%# <button class="btn"><%= link_to "Sign up!", signup_path %></button>
      </div>
    </section>

    <!-- XXX Site title -->

    <!-- blog carousel -->
    <%= render 'news/index' %>
    
    
    <!-- XX blog carousel -->

    <!-- Site Content -->

    <section class="container">
      <div class="site-content">
        <div class="posts">
          <%= will_paginate @reports, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
            <% @reports.each do |report| %>
              <div class="post-content" data-aos="zoom-in" data-aos-delay="200">
                <div class="post-image">
                  <div>
                    <%= image_tag report.image.url, class:"img", alt:"blog1" %>
                  </div>
                  <div class="post-info flex-row">
                    <span><i class="fas fa-user text-gray"></i>&nbsp;&nbsp;
                      <% if report.user %>
                        by <%= link_to report.user.username, user_path(report.user) %>
                      <% end %>
                    </span>
                    <span><i class="fas fa-calender-alt text-gray"></i>&nbsp;&nbsp;<%= time_ago_in_words(report.created_at) %> ago,</span>
                    <span>2 Comments</span>
                  </div>
                </div>
                <div class="post-title"><%= link_to report.title, report_path(report) %>
                  <p><%= truncate(report.description, length: 100) %>
                  </p>
                  <button class="btn post-btn"><%= link_to "Read More", report_path(report) %>&nbsp;<i class="fas fa-arrow-right"></i></button>
                  <% if logged_in? && (report.user == current_user || current_user.admin?) %>
                    <%= link_to "Edit", edit_report_path(report), class: "btn btn-outline-info" %>
                    <%= link_to "Delete", report_path(report), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                  <% end %>
                </div>
              </div>
              
            <% end %>
          <%= will_paginate @reports, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

        </div>
        <aside class="sidebar">
          <div class="category">
            <h2>Category</h2>
            <ul class="category-list" >
              <li class="list-items" data-aos="fade-left" data-aos-delay="100">
                <a href="#">Software</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="200">
                <a href="#">Technology</a>
                <span>(02)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="300">
                <a href="#">Lifestyle</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="400">
                <a href="#">Shopping</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="500">
                <a href="#">Food</a>
                <span>(05)</span>
              </li>
            </ul>
          </div>

          <div class="popular-post">
            <h2>Popular Post</h2>
            <% @random.each do |report| %>
            
              <div class="post-content" data-aos="flip-up" data-aos-delay="200">
                <div class="post-image">
                  <div>
                    <%= image_tag report.image.url, class:"img", alt:"blog1" %>
                  </div>
                  <div class="post-info flex-row">
                    <span><i class="fas fa-calendar-alt text-gray"></i>&nbsp;&nbsp;<%= report.created_at.strftime('%Y-%m-%d') %></span>
                    <span>2 Comments</span>
                  </div>
                </div>
                <div class="post-title">
                  <a><%= link_to report.title, report_path(report) %></a>
                </div>
              </div>
            <% end %>
          </div>
          
          <div class="newsletter" data-aos="fade-up" data-aos-delay="300">
            <h2>Newsletter</h2>
            <div class="form-element">
              <input type="text" class="input-element" placeholder="Email">
              <button class="btn form-btn">Subscribe</button>
            </div>
          </div>
          <div class="popular-tags">
            <h2>Popular Tags</h2>
            <div class="tags flex-row">
              <span class="tag" data-aos="flip-up" data-aos-delay="100">Software</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="200">Technology</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="300">Travel</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="400">Illustration</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="500">Design</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="600">Lifestyle</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="700">Love</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="800">Project</span>
            </div>
          </div>
        </aside>
      </div>
    </section>

    <!-- XX Site Content -->

  </main>

  <!--  xxx  main site section -->

app/views/reports/_report.html.erb
<div>
  <div class="title-name">
    <h1>Listing all reports</h1>
  </div>
  <main>
  <!-- Site Content -->
    <section class="container">
      <div class="site-content">
        <div class="posts">
          <%= will_paginate @reports, previous_label: '<', next_label: '>', inner_window: 1 %>
            <% @reports.each do |report| %>
              <div class="post-content" data-aos="zoom-in" data-aos-delay="200">
                <div class="post-image">
                  <div>
                    <%= image_tag report.image.url, class:"img", alt:"blog1" %>
                  </div>
                  <div class="post-info flex-row">
                    <span><i class="fas fa-user text-gray"></i>&nbsp;&nbsp;
                      <% if report.user %>
                        by <%= link_to report.user.username, user_path(report.user) %>
                      <% end %>
                    </span>
                    <span><i class="fas fa-calender-alt text-gray"></i>&nbsp;&nbsp;<%= time_ago_in_words(report.created_at) %> ago,</span>
                    <span>2 Comments</span>
                  </div>
                </div>
                <div class="post-title"><%= link_to report.title, report_path(report) %>
                  <p><%= truncate(report.description, length: 100) %>
                  </p>
                  <button class="btn post-btn"><%= link_to "Read More", report_path(report) %>&nbsp;<i class="fas fa-arrow-right"></i></button>
                  <% if logged_in? && (report.user == current_user || current_user.admin?) %>
                    <%= link_to "Edit", edit_report_path(report), class: "btn btn-outline-info" %>
                    <%= link_to "Delete", report_path(report), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                  <% end %>
                </div>
              </div>
              
            <% end %>
          <%= will_paginate @reports, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

        </div>
        <aside class="sidebar">
          <div class="category">
            <h2>Category</h2>
            <ul class="category-list" >
              <li class="list-items" data-aos="fade-left" data-aos-delay="100">
                <a href="#">Software</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="200">
                <a href="#">Technology</a>
                <span>(02)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="300">
                <a href="#">Lifestyle</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="400">
                <a href="#">Shopping</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="500">
                <a href="#">Food</a>
                <span>(05)</span>
              </li>
            </ul>
          </div>

          <div class="popular-post">
            <h2>Popular Post</h2>
            <% @random.each do |report| %>
            
              <div class="post-content" data-aos="flip-up" data-aos-delay="200">
                <div class="post-image">
                  <div>
                    <%= image_tag report.image.url, class:"img", alt:"blog1" %>
                  </div>
                  <div class="post-info flex-row">
                    <span><i class="fas fa-calendar-alt text-gray"></i>&nbsp;&nbsp;January 14,2019</span>
                    <span>2 Comments</span>
                  </div>
                </div>
                <div class="post-title">
                  <a><%= link_to report.title, report_path(report) %></a>
                </div>
              </div>
            <% end %>
          </div>
          
          <div class="newsletter" data-aos="fade-up" data-aos-delay="300">
            <h2>Newsletter</h2>
            <div class="form-element">
              <input type="text" class="input-element" placeholder="Email">
              <button class="btn form-btn">Subscribe</button>
            </div>
          </div>
          <div class="popular-tags">
            <h2>Popular Tags</h2>
            <div class="tags flex-row">
              <span class="tag" data-aos="flip-up" data-aos-delay="100">Software</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="200">Technology</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="300">Travel</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="400">Illustration</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="500">Design</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="600">Lifestyle</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="700">Love</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="800">Project</span>
            </div>
          </div>
        </aside>
      </div>
    </section>
    <!-- XX Site Content -->
  </main>
</div> 

app/views/reports/show.html.erb
<div class="title-name">
  <h1>Showing report details</h1>
</div>

<div>
  <main>
    <!-- Site Content -->
    <section class="container">
      <div class="site-content">
        <div class="posts">
          <div class="post-content" data-aos="zoom-in" data-aos-delay="200">
            <div class="post-image">
              <div>
                <%= image_tag @report.image.url, class:"img", alt:"blog1" %>
              </div>
              <div class="post-info flex-row">
                <span><i class="fas fa-user text-gray"></i>&nbsp;&nbsp;
                  <%= @report.user.username if @report.user %>
                </span>
                <span><i class="fas fa-calender-alt text-gray"></i>&nbsp;&nbsp;<%= time_ago_in_words(@report.created_at) %> ago,</span>
                <span>2 Comments</span>
              </div>
            </div>
            <div class="post-title"><%= link_to @report.title, report_path(@report) %>
              <p><%= simple_format(@report.description, length: 100000) %>
              </p>
              <% if logged_in? && (@report.user == current_user || current_user.admin?) %>
                <button class="btn post-btn"><%= link_to "Edit", edit_report_path(@report) %>&nbsp;</button>
                <button class="btn post-btn"><%= link_to "Delete", report_path(@report),class:"red-btn", method: :delete, data: {confirm: "Are you sure?"} %>&nbsp;</button>
              <% end %>
            </div>
          </div>

      

        </div>
        <aside class="sidebar">
          <div class="category">
            <h2>Category</h2>
            <ul class="category-list" >
              <li class="list-items" data-aos="fade-left" data-aos-delay="100">
                <a href="#">Software</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="200">
                <a href="#">Technology</a>
                <span>(02)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="300">
                <a href="#">Lifestyle</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="400">
                <a href="#">Shopping</a>
                <span>(05)</span>
              </li>
              <li class="list-items" data-aos="fade-left" data-aos-delay="500">
                <a href="#">Food</a>
                <span>(05)</span>
              </li>
            </ul>
          </div>

          <div class="popular-post">
            <h2>Popular Post</h2>
            <% @random.each do |report| %>
              <div class="post-content" data-aos="flip-up" data-aos-delay="200">
                <div class="post-image">
                  <div>
                    <%= image_tag report.image.url, class:"img", alt:"blog1" %>
                  </div>
                  <div class="post-info flex-row">
                    <span><i class="fas fa-calendar-alt text-gray"></i>&nbsp;&nbsp;January 14,2019</span>
                    <span>2 Comments</span>
                  </div>
                </div>
                <div class="post-title">
                  <a><%= link_to report.title, report_path(report) %></a>
                </div>
              </div>
            <% end %>
          </div>
          
          <div class="newsletter" data-aos="fade-up" data-aos-delay="300">
            <h2>Newsletter</h2>
            <div class="form-element">
              <input type="text" class="input-element" placeholder="Email">
              <button class="btn form-btn">Subscribe</button>
            </div>
          </div>
          <div class="popular-tags">
            <h2>Popular Tags</h2>
            <div class="tags flex-row">
              <span class="tag" data-aos="flip-up" data-aos-delay="100">Software</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="200">Technology</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="300">Travel</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="400">Illustration</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="500">Design</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="600">Lifestyle</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="700">Love</span>
              <span class="tag" data-aos="flip-up" data-aos-delay="800">Project</span>
            </div>
          </div>
        </aside>
      </div>
    </section>
    <!-- XX Site Content -->
  </main>
</div>

app/views/users/index.html.erb
<h1></h1>

<div>
  <div class="login">
    <div class="login-triangle"></div>
    <h1 class="login-header">Alpha Bloggers</h1>
    <div class="login-container">
      <div class="img-profile">
        <div>
          <% @users.each do |user| %>
            <div>
              <div>
                <div>
                  <div>
                    <h1><%= link_to user.username, user %></h1>
                  </div>
                  <div>
                    <h5>
                      <%= link_to gravatar_for(user, size: 150), user %>
                    </h5>
                    <p><%= pluralize(user.reports.count, "report") %></p>
                    <h2><%= link_to "View profile", user %></h2>
                    <% if logged_in? %>
                      <% if user == current_user %>
                        <h2><%= link_to "Edit profile", edit_user_path(user) %></h2>
                      <% end %>
                      <% if current_user.admin? %>
                        <h2><%= link_to "Delete profile", user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } %></h2>
                      <% end %>
                    <% end %>
                  </div>
                  <div>
                    <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <div class="login">
    <div class="login-triangle"></div>
    <h1 class="login-header"><%= @user.username %>'s profile</h1>
    <div class="login-container">
      <div class="img-profile">
        <%= gravatar_for @user, size: 200 %>
        <% if logged_in? && @user == current_user %>
          <h2><%= link_to "Edit profile", edit_user_path(@user) %></h2>
          <h2><%= link_to "Delete profile", user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } %></h2>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render 'reports/report' %>